<a href="https://colab.research.google.com/github/Es-YES-Ye/Python/blob/main/%ED%86%B5%EA%B3%84%EB%B6%84%EC%84%9D%EC%8B%9C%EA%B0%81%ED%99%94_Numpy_%EC%86%8C%EA%B0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy 소개

In [26]:
import numpy as np

numpy는 선형 시퀀스(튜플, 리스트)를 배열 개체로 취급

한 줄로 쭉 들어가있는 데이터의 집합 -> 선형 시퀀스

In [2]:
ls = [1,2,3]
arr = np.array(ls)
print(arr)

[1 2 3]


In [4]:
#직접 만들 수도 있고, 리스트 변수를 넣어서 만들 수도 있다

arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [5]:
print("구조 : ", arr.shape)
print("차원 : ", arr.ndim)

구조 :  (3,)
차원 :  1


#다차원 배열
tensor 
tensorflow 모듈

In [6]:
ls = [[1,2,3], [4,5,6], [7,8,9], [10,11,12]]
arr = np.array(ls)
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
print("구조 : ", arr.shape)
print("차원 : ", arr.ndim)

구조 :  (4, 3)
차원 :  2


#다양한 방법의 생성

In [10]:
#전체 구성요소가 zero로 되어있는 걸 원할 때
#초기값을 0으로 정해놓고 값을 나중에 변경할 때 사용한다.
#https://numpy.org/doc/stable/reference/generated/numpy.zeros.html?highlight=numpy%20zeros#numpy.zeros

z_arr = np.zeros(10)
print(z_arr)
print("구조 : ", z_arr.shape)
print("차원 : ", z_arr.ndim)
print("원소형식 : ", z_arr.dtype)
#64비트짜리 float

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
구조 :  (10,)
차원 :  1
원소형식 :  float64


In [ ]:
#원하는 타입으로 지정하면 원하는 형식으로 만들 수 있다.

z_arr = np.zeros(10, dtype=int) 
print(z_arr)
print("구조 : ", z_arr.shape)
print("차원 : ", z_arr.ndim)
print("원소형식 : ", z_arr.dtype)


In [11]:
#
z_arr = np.zeros((2,3))
print(z_arr)
print("구조 : ", z_arr.shape)
print("차원 : ", z_arr.ndim)
print("원소형식 : ", z_arr.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
구조 :  (2, 3)
차원 :  2
원소형식 :  float64


In [17]:
def view_arr_info(arr):
  print(arr)
  print("구조 : ", arr.shape)
  print("차원 : ", arr.ndim)
  print("원소형식 : ", arr.dtype)

In [18]:
z_arr = np.zeros((3,2,4), dtype=int)
view_arr_info(z_arr)

[[[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]]
구조 :  (3, 2, 4)
차원 :  3
원소형식 :  int64


In [19]:
o_arr = np.ones(10)
view_arr_info(o_arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
구조 :  (10,)
차원 :  1
원소형식 :  float64


In [21]:
s_arr = np.arange(100)
view_arr_info(s_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
구조 :  (100,)
차원 :  1
원소형식 :  int64


In [22]:
s_arr = np.arange(50, 100)
view_arr_info(s_arr)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]
구조 :  (50,)
차원 :  1
원소형식 :  int64


In [23]:
r_arr = np.random.randint(0,100,size=10,dtype=int)
view_arr_info(r_arr)

#https://numpy.org/doc/stable/user/basics.creation.html

[66 57 16 34 44 31 33 95 70 10]
구조 :  (10,)
차원 :  1
원소형식 :  int64


#기본적인 사용

In [33]:
a1 = np.arange(1,100)
view_arr_info(a1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
구조 :  (99,)
차원 :  1
원소형식 :  int64


In [34]:
print(a1[4]) #인덱스를 통해 원소에 접근
a1[4] = 9
print(a1[4])

5
9


In [35]:
print(a1[2:8])
print(a1[:8])
print(a1[8:])


[3 4 9 6 7 8]
[1 2 3 4 9 6 7 8]
[ 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32
 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56
 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80
 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [39]:
a1=np.arange(0,100)
view_arr_info(a1)
a2=a1.reshape(5,20)
view_arr_info(a2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
구조 :  (100,)
차원 :  1
원소형식 :  int64
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]
구조 :  (5, 20)
차원 :  2
원소형식 :  int64


In [40]:
print(a2[0]) #인덱스 0인 원소 : 리스트[0,1,2,...,19]
print(a2[0][0]) #인덱스 0인 원소 : 리스트[0,1,2,3,...,19]의 인덱스 2인 원소

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
0


In [ ]:
#음의 정수로 인덱스를 표현하면 뒤에서부터 접근(-1부터 시작)
print(a2[0][-1]) #인덱스 0인 원소 : 리스트[0,1,2,...,19]의 인덱스 -1인 원소

#구조 변경

In [41]:
a1=np.arange(100)
view_arr_info(a1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
구조 :  (100,)
차원 :  1
원소형식 :  int64


In [43]:
a4=a1.reshape((5,2,5,-1))
view_arr_info(a4)

[[[[ 0  1]
   [ 2  3]
   [ 4  5]
   [ 6  7]
   [ 8  9]]

  [[10 11]
   [12 13]
   [14 15]
   [16 17]
   [18 19]]]


 [[[20 21]
   [22 23]
   [24 25]
   [26 27]
   [28 29]]

  [[30 31]
   [32 33]
   [34 35]
   [36 37]
   [38 39]]]


 [[[40 41]
   [42 43]
   [44 45]
   [46 47]
   [48 49]]

  [[50 51]
   [52 53]
   [54 55]
   [56 57]
   [58 59]]]


 [[[60 61]
   [62 63]
   [64 65]
   [66 67]
   [68 69]]

  [[70 71]
   [72 73]
   [74 75]
   [76 77]
   [78 79]]]


 [[[80 81]
   [82 83]
   [84 85]
   [86 87]
   [88 89]]

  [[90 91]
   [92 93]
   [94 95]
   [96 97]
   [98 99]]]]
구조 :  (5, 2, 5, 2)
차원 :  4
원소형식 :  int64


In [ ]:
a1=np.arange(784)
view_arr_info(a1)

In [ ]:
a2=a1.reshape(28,-1) #-1을 주면 알아서 배열을 해준다.
view_arr_info(a2) 

#쉬어가는 코너

In [61]:
from tensorflow import keras

In [62]:
data = keras.datasets.mnist.load_data() #손글씨 데이터를 다운로드

In [63]:
train_data, test_data = data #학습용 데이터, 평가용 데이터로 분리
image_train, label_train = train_data #이미지, 실제값

In [64]:
print(image_train.shape) #너비가 28 높이가 28 의 흑백이미지
print(label_train.shape) #

(60000, 28, 28)
(60000,)


In [65]:
for r in range(28):
  for c in range(28):
    if(image_train[0][r][c] == 0):
      print("  ",end='')
    else:
      print("■",end='')
  print()
print(label_train[0])

                                                        
                                                        
                                                        
                                                        
                                                        
                        ■■■■■■■■■■■■        
                ■■■■■■■■■■■■■■■■        
              ■■■■■■■■■■■■■■■■          
              ■■■■■■■■■■■                    
                ■■■■■■■  ■■                    
                  ■■■■■                            
                      ■■■■                          
                      ■■■■                          
                        ■■■■■■                    
                          ■■■■■■                  
                            ■■■■■■                
                              ■■■■■                
                                  ■■■■              
                            ■■■■■■■              
                        ■■■■