<a href="https://colab.research.google.com/github/Es-YES-Ye/Python/blob/main/%ED%86%B5%EA%B3%84%EB%B6%84%EC%84%9D%EC%8B%9C%EA%B0%81%ED%99%94_Numpy_More.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#행렬의 기본 연산

In [ ]:
import numpy as np

In [ ]:
#리스트는 우리가 원하는 행렬 연산이 안 된다.
ls1=[1,2]
ls2=[3,4]
ls3=ls1+ls2
print(ls3) 

[1, 2, 3, 4]


In [ ]:
#행렬 연산을 위한 함수를 만들어야 한다.

def add(l1, l2):
  assert len(l1)==len(l2), "더하기 연산을 위하서는 요소의 길이가 같아야 한다."
  re=[]
  for i in range(len(l1)):
    re.append(l1[i]+l2[i])
  return re   

In [ ]:
ls1=[1,2]
ls2=[3,4]
ls3=add(ls1,ls2)
print(ls3)

[4, 6]


#assert

만든 함수를 테스트하기 위한 목적

assert 조건, '메시지'

'메시지'는 생략할 수 있다.

assert 뒤의 조건이 True 가 아니면 AeertError가 발생한다.

In [ ]:
#ls 목록에 있는 요소의 합계를 구하는 함수
def calsum(ls):
  s=0
  for e in ls:
    s+=e
  return s

In [ ]:
assert calsum([1,2,3,2])==8, "calsum([1,2,3,2]) 값은 8이어야 합니다."


In [ ]:
s=0
for i in range(10):
  s += i

assert s==55, "s는 55여야 합니다." #AssertionError: s는 55여야 합니다.

AssertionError: ignored

In [ ]:
#numpy는 행렬 연산이 이미 만들어져있다.
n1=np.array([1,2])
n2=np.array([3,4])
n3=n1+n2
print(n3)

In [ ]:
n3=n1-n2
print(n3)

In [ ]:
#리스트는 값에 3을 곱하는 게 아니고 리스트를 세 번 반복한다.

ls1 = [1,2,3,4]
ls2 = ls1 * 3
print(ls2)

In [ ]:
#numpy는 행렬 값에 3씩 곱하는 계산이 가능하다

n1 = np.array([1,2,3,4])
n2 = n1*3
print(n2)

In [ ]:
#모든 원소들을 해당하는 표준편자로 나눠주는 작업
n2 = n1/3
print(n2)

[0.33333333 0.66666667 1.         1.33333333]


만약 n1에서 500 이상의 숫자만 추출하고 싶다면

In [27]:
n1 = np.random.randint(1, 1000, 100, dtype=int) #1부터 천까지 중에서 100개, 인트타입으로 출력
print(n1)

[451 946 976  55 709 114 656 403  93 602 572 424 313 497 335 649 365 794
 845 780 482 721 897 864  83 454  36 830  54 762 753 546 460 863 448 164
 894 262 163 983 206 151 988 999 773 198 266 261 858  24 418 622 344 973
 240 619 437 830  38 976 123 108 499 287 917 755 936 398  78 485 861 772
 769 328 987 651 433  52 344 852 182 140  31 231 896 452 854 283 151 867
 497 282  11 353 905 667  28 897 875 725]


In [24]:
n2 = n1>500
print(n2)

[ True  True  True False  True False  True  True  True  True  True False
  True False False  True  True  True  True False False False  True  True
  True  True False False  True  True False False False  True  True  True
 False  True  True False  True  True False False False  True False  True
 False  True False  True  True  True False  True False False False  True
 False  True  True False  True  True False  True  True False False False
 False  True False  True False False  True  True  True False  True False
  True  True False False  True False False False  True False False  True
  True False  True False]


In [25]:
n3 = n1[n2]
print(n3)

[542 643 858 960 636 786 995 888 574 600 928 712 583 686 521 580 936 693
 867 638 771 517 689 878 716 681 610 938 867 750 649 843 880 519 897 783
 746 615 796 523 964 580 836 808 766 864 511 816 617 974 575 972 636 826]


내적함수

In [29]:
n1=np.array([[1,2],[3,4]])
n2=np.array([4,5])
n3=np.dot(n1, n2)
print(n3)

[14 32]


In [30]:
n1 = np.array([1,2,3,4])
n2 = n1.reshape((2,2))
print(n2)

[[1 2]
 [3 4]]


In [31]:
#전치행렬 : 행과 열을 교환하여 얻는 행렬

n3=np.transpose(n2)
print(n3)

[[1 3]
 [2 4]]


In [34]:
#반전 (원소의 메모리)

n3=np.invert(n2)
print(n3)

[[-2 -3]
 [-4 -5]]


In [35]:
#역행렬 : 각행렬 AA의 곱셈에 대한 역원 A^{-1}A −1
#A*B = 단위행렬(E) 일 때, B를 A의 역행렬 A-1로 표시

n3 = np.linalg.inv(n2)

In [36]:
n4 = n2.dot(n3)
print(n4)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


통계 관련

In [37]:
n1 = np.random.randint(1, 100, 30, dtype=int)
print(n1)
print("길이 : ", len(n1))
print("평균 : ", n1.mean())

[73 88 64  5 57 71 94 62  4 71 43 50 58 50 96 79 85 58 89 77 78 39 64 35
 30 49 56 29 92 27]
길이 :  30


In [38]:
n2=n1-n1.mean()
print("수평 이동한 후 평균 : ", n2.mean())

수평 이동한 후 평균 :  -1.8947806286936005e-15


In [40]:
print("최대값 위치 : ", n1.argmax())
print("최대값 : ", n1[16])
print("최대값 : ", n1.max())


최대값 위치 :  14
최대값 :  85
최대값 :  96


In [41]:
print("분산 : ", n1.var())
print("표준편차 : ", n1.std())

분산 :  598.09
표준편차 :  24.455878638887626


In [42]:
n2 = n1/n1.std()
print("스케일 조절한 후 표준 편차 : " , n2.std())

스케일 조절한 후 표준 편차 :  1.0


In [48]:
print("최솟값 : ", n1.min()) #n1으로 접근은 객체의 멤버메소드
print("최대값 : ", np.median(n1)) #np로 접근은 정적메소드
print("1/4분위값 : ",np.percentile(n1, 0.25)) 
print("3/4분위값 : ", np.percentile(n1, 0.75))

최솟값 :  4
최대값 :  60.0
1/4분위값 :  4.0725
3/4분위값 :  4.2175


In [49]:
print(n1)
print()
print("누적 합: ", np.cumsum(n1))

[73 88 64  5 57 71 94 62  4 71 43 50 58 50 96 79 85 58 89 77 78 39 64 35
 30 49 56 29 92 27]

누적 합:  [  73  161  225  230  287  358  452  514  518  589  632  682  740  790
  886  965 1050 1108 1197 1274 1352 1391 1455 1490 1520 1569 1625 1654
 1746 1773]


In [50]:
print(n1)
print()
print("누적 곱 : ", np.cumprod(n1))

[73 88 64  5 57 71 94 62  4 71 43 50 58 50 96 79 85 58 89 77 78 39 64 35
 30 49 56 29 92 27]

누적 곱 :  [                  73                 6424               411136
              2055680            117173760           8319336960
         782017674240       48485095802880      193940383211520
    13769767208017920   592099989944770560 -7288488650180575232
  1542771984846323712  3351622947477979136  8161153704823619584
  -904899898768359424 -3129515100472344576  2955564909699530752
  4790859931324514304   -38666762203430912 -3016007451867611136
 -6943826180579524608 -1683017788060336128 -3565390360983109632
  3718753612764020736 -2248513711658500096  3210440663090855936
   869058861087064064  6166438925171687424   473154316249595904]
