<a href="https://colab.research.google.com/github/Es-YES-Ye/Python/blob/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.array(['1.5', '0.62', '10','3.14','32'])

array(['1.5', '0.62', '10', '3.14', '32'], dtype='<U4')

In [ ]:
str_a1 = np.array(['1.567', '0.123', '5.125', '9', '7'])
num_a1 = str_a1.astype(float)
str_a1.dtype, num_a1, num_a1.dtype 

(dtype('<U5'), array([1.567, 0.123, 5.125, 9.   , 7.   ]), dtype('float64'))

In [ ]:
num_f1 = np.array([10, 21, 0.546, 4.32, 5.77])
num_i1 = num_f1.astype(int)
num_f1.dtype, num_i1, num_i1.dtype

(dtype('float64'), array([10, 21,  0,  4,  5]), dtype('int64'))

In [ ]:
np.random.rand(2,3)

array([[0.78632522, 0.09948503, 0.18608532],
       [0.09413828, 0.93450303, 0.60230331]])

In [ ]:
np.random.rand(2,3,4)

array([[[0.41809531, 0.77766916, 0.31651167, 0.46038275],
        [0.44362567, 0.86441232, 0.02570507, 0.74017634],
        [0.0429259 , 0.8441574 , 0.00161534, 0.42023719]],

       [[0.16687236, 0.59389968, 0.68419174, 0.1071643 ],
        [0.6411809 , 0.45466651, 0.04749948, 0.67989057],
        [0.0253963 , 0.72453955, 0.68718508, 0.17024779]]])

In [ ]:
np.random.randint(1,30)

22

In [ ]:
np.random.randint(10, size=(3,4))

array([[6, 9, 2, 2],
       [9, 7, 1, 4],
       [7, 9, 5, 0]])

In [ ]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])

In [ ]:
print(arr1+arr2
, arr1-arr2
, arr2*2
, arr2**2)
print(arr1*arr2
, arr1/arr2)
print(arr1/(arr2**2)
)
print(arr1>20)

In [ ]:
arr3=np.arange(5)
arr3

In [ ]:
arr3.sum(), arr3.mean()

In [ ]:
arr3.std(), arr3.var()

In [ ]:
arr3.min(), arr3.max()

In [ ]:
arr3.cumsum(), arr3.cumprod()