<a href="https://colab.research.google.com/github/Es-YES-Ye/Python/blob/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EB%94%A5%EB%9F%AC%EB%8B%9D_%EC%B4%9D%EA%B4%84(%EB%A6%AC%EC%8A%A4%ED%8A%B8%2C%EB%AA%A8%EB%93%88).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

리스트 

In [ ]:
ls1 = [x for x in range(10)]
ls2 = [x for x in range(10) if x%2 == 0]
ls3 = [x if x%2 == 0 else (-1) for x in range(10)]

ls1, ls2, ls3

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [0, 2, 4, 6, 8],
 [0, -1, 2, -1, 4, -1, 6, -1, 8, -1])

In [ ]:
def calculate(xs):
  s =0
  for x in xs:
    s += x
  return s, s/len(xs)

In [ ]:
s,_ = calculate([1,2,3,4,5,6,7,8,9,10])
print(f"합계:{s:010d}")

합계:0000000055


In [ ]:
data = 2,3
print(type(data))

<class 'tuple'>


In [ ]:
a,b = data
a,b

(2, 3)

In [8]:
import sys
sys.path.append('/content/')

In [9]:
import foo

In [10]:
foo.A()

A


from 모듈이름 import 모듈 내에 있는 것 중에 간단히 사용할 이름

In [11]:
import soo

In [12]:
s = soo.Soo()

Soo


In [13]:
from soo import Soo

In [14]:
s = Soo()

Soo


대표 모듈

In [15]:
import numpy as np

In [17]:
ls1 = [1,2,3,4]
ls2 = [3,4,5,6]

ls3 = ls1+ls2 # + 연산은 제공하지만 행렬 간의 더하기 연산은 아님
ls3

[1, 2, 3, 4, 3, 4, 5, 6]

In [ ]:
#ls3 = ls2-ls1 행렬 사이의 빼기 연산 제공하지 않음

In [18]:
ls3 = ls1*4 # * 연산도 행렬과 정수 사이의 연산이 아님
ls3

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [20]:
ar1= np.array(ls1)
ar2= np.array(ls2)
ar3 = ar1 + ar2
ar3

array([ 4,  6,  8, 10])

In [21]:
ar3 = ar1 + ar2 #행렬 사이의 + 연산 제공
ar3

array([ 4,  6,  8, 10])

In [22]:
ar3 = ar2 - ar1 #행렬 사이의 - 연산 제공
ar3

array([2, 2, 2, 2])

In [23]:
ar3 = ar2*4 #행렬과 정수 사이의 x 연산 제공
ar3

array([12, 16, 20, 24])

In [24]:
ar3 = ar1 @ ar2 #행렬과 행렬 사이의 내적 연산
ar3

50

In [25]:
ar3 = ar1 * ar2 #행렬 사이의 곱하기 연산
ar3

array([ 3,  8, 15, 24])

In [26]:
ar3 = ar1.dot(ar2) #내적
ar3

50

In [27]:
ls = [[1,2,3], [2], [4,5,6,7,8]]
ls

[[1, 2, 3], [2], [4, 5, 6, 7, 8]]

In [28]:
ar = np.arange(100)
ar.shape

(100,)

In [29]:
ar2 = ar.reshape(2, 50)
ar2.shape

(2, 50)

In [30]:
ar2.dtype

dtype('int64')

In [32]:
ar = np.array([1,2,3,5.])
print(type(ar[0]))

<class 'numpy.float64'>


In [33]:
ls = [1,2,3,5.]
print(type(ls[0]))

<class 'int'>


In [36]:
ar = np.random.randn(1000)
ar.sum(), ar.mean(), np.median(ar), np.quantile(ar, 0.25)

(-19.20314279082759,
 -0.01920314279082759,
 0.028496062181171095,
 -0.6599604783091989)

In [37]:
ar1 = [1,2,3,4]
ar2 = [4,5,6,7]
cv = np.cov(ar1, ar2)
print(cv[0,0]) #ar1과 ar1 사이의 공분산
print(cv[0,1]) #ar1과 ar2 사이의 공분산
print(cv[1,0]) #ar2과 ar1 사이의 공분산
print(cv[1,1]) #ar2과 ar2 사이의 공분산

array([[1.66666667, 1.66666667],
       [1.66666667, 1.66666667]])

In [39]:
cv[0,1]/(np.std(ar1)*np.std(ar2)) #상관계수

1.333333333333333

In [38]:
import pandas as pd

In [41]:
df = pd.read_csv('/content/sample_data/california_housing_test.csv')
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0   
1       -118.30     34.26                43.0       1510.0           310.0   
2       -117.81     33.78                27.0       3589.0           507.0   
3       -118.36     33.82                28.0         67.0            15.0   
4       -119.67     36.33                19.0       1241.0           244.0   
...         ...       ...                 ...          ...             ...   
2995    -119.86     34.42                23.0       1450.0           642.0   
2996    -118.14     34.06                27.0       5257.0          1082.0   
2997    -119.70     36.30                10.0        956.0           201.0   
2998    -117.12     34.10                40.0         96.0            14.0   
2999    -119.63     34.42                42.0       1765.0           263.0   

      population  households  median_income  median_house_value  
0         1537.0       606.0         6.6085            344700.0  
1          809.0       277.0         3.5990            176500.0  
2         1484.0       495.0         5.7934            270500.0  
3           49.0        11.0         6.1359            330000.0  
4          850.0       237.0         2.9375             81700.0  
...          ...         ...            ...                 ...  
2995      1258.0       607.0         1.1790            225000.0  
2996      3496.0      1036.0         3.3906            237200.0  
2997       693.0       220.0         2.2895             62000.0  
2998        46.0        14.0         3.2708            162500.0  
2999       753.0       260.0         8.5608            500001.0  

[3000 rows x 9 columns]

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB


In [43]:
df.describe()

longitude    latitude  housing_median_age   total_rooms  \
count  3000.000000  3000.00000         3000.000000   3000.000000   
mean   -119.589200    35.63539           28.845333   2599.578667   
std       1.994936     2.12967           12.555396   2155.593332   
min    -124.180000    32.56000            1.000000      6.000000   
25%    -121.810000    33.93000           18.000000   1401.000000   
50%    -118.485000    34.27000           29.000000   2106.000000   
75%    -118.020000    37.69000           37.000000   3129.000000   
max    -114.490000    41.92000           52.000000  30450.000000   

       total_bedrooms    population  households  median_income  \
count     3000.000000   3000.000000  3000.00000    3000.000000   
mean       529.950667   1402.798667   489.91200       3.807272   
std        415.654368   1030.543012   365.42271       1.854512   
min          2.000000      5.000000     2.00000       0.499900   
25%        291.000000    780.000000   273.00000       2.544000   
50%        437.000000   1155.000000   409.50000       3.487150   
75%        636.000000   1742.750000   597.25000       4.656475   
max       5419.000000  11935.000000  4930.00000      15.000100   

       median_house_value  
count          3000.00000  
mean         205846.27500  
std          113119.68747  
min           22500.00000  
25%          121200.00000  
50%          177650.00000  
75%          263975.00000  
max          500001.00000

In [44]:
ar1 = np.array([1,2,3,-4,5,-2])
filter = ar1>=0
far = ar1[filter]
far

array([1, 2, 3, 5])

In [47]:
far = ar1[ar1>=0]
far

array([1, 2, 3, 5])

In [48]:
temp = ar1>=0
temp

array([ True,  True,  True, False,  True, False])

In [49]:
far = ar1[temp]
far

array([1, 2, 3, 5])

In [54]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0   
1       -118.30     34.26                43.0       1510.0           310.0   
2       -117.81     33.78                27.0       3589.0           507.0   
3       -118.36     33.82                28.0         67.0            15.0   
4       -119.67     36.33                19.0       1241.0           244.0   
...         ...       ...                 ...          ...             ...   
2995    -119.86     34.42                23.0       1450.0           642.0   
2996    -118.14     34.06                27.0       5257.0          1082.0   
2997    -119.70     36.30                10.0        956.0           201.0   
2998    -117.12     34.10                40.0         96.0            14.0   
2999    -119.63     34.42                42.0       1765.0           263.0   

      population  households  median_income  median_house_value  
0         1537.0       606.0         6.6085            344700.0  
1          809.0       277.0         3.5990            176500.0  
2         1484.0       495.0         5.7934            270500.0  
3           49.0        11.0         6.1359            330000.0  
4          850.0       237.0         2.9375             81700.0  
...          ...         ...            ...                 ...  
2995      1258.0       607.0         1.1790            225000.0  
2996      3496.0      1036.0         3.3906            237200.0  
2997       693.0       220.0         2.2895             62000.0  
2998        46.0        14.0         3.2708            162500.0  
2999       753.0       260.0         8.5608            500001.0  

[3000 rows x 9 columns]

In [53]:
lt = df['latitude']
print(type(lt))
lt

<class 'pandas.core.series.Series'>


0       37.37
1       34.26
2       33.78
3       33.82
4       36.33
        ...  
2995    34.42
2996    34.06
2997    36.30
2998    34.10
2999    34.42
Name: latitude, Length: 3000, dtype: float64

In [58]:
t_rd = df[['total_rooms','total_bedrooms']]
print(type(t_rd))
t_rd

<class 'pandas.core.frame.DataFrame'>


total_rooms  total_bedrooms
0          3885.0           661.0
1          1510.0           310.0
2          3589.0           507.0
3            67.0            15.0
4          1241.0           244.0
...           ...             ...
2995       1450.0           642.0
2996       5257.0          1082.0
2997        956.0           201.0
2998         96.0            14.0
2999       1765.0           263.0

[3000 rows x 2 columns]

In [60]:
rd_arr = t_rd.to_numpy()
print(type(rd_arr))
rd_arr

<class 'numpy.ndarray'>


array([[3885.,  661.],
       [1510.,  310.],
       [3589.,  507.],
       ...,
       [ 956.,  201.],
       [  96.,   14.],
       [1765.,  263.]])

In [61]:
ls = rd_arr.tolist()
print(type(ls))
ls

<class 'list'>


[[3885.0, 661.0],
 [1510.0, 310.0],
 [3589.0, 507.0],
 [67.0, 15.0],
 [1241.0, 244.0],
 [1018.0, 213.0],
 [1009.0, 225.0],
 [2310.0, 471.0],
 [3080.0, 617.0],
 [2402.0, 632.0],
 [972.0, 249.0],
 [736.0, 166.0],
 [1089.0, 182.0],
 [3936.0, 694.0],
 [2097.0, 325.0],
 [161.0, 40.0],
 [570.0, 123.0],
 [3077.0, 607.0],
 [1590.0, 196.0],
 [8814.0, 1307.0],
 [1445.0, 256.0],
 [1775.0, 296.0],
 [2994.0, 543.0],
 [2021.0, 528.0],
 [6131.0, 1040.0],
 [1401.0, 218.0],
 [3587.0, 1030.0],
 [2612.0, 418.0],
 [4845.0, 1609.0],
 [3078.0, 954.0],
 [1195.0, 220.0],
 [1617.0, 493.0],
 [3442.0, 705.0],
 [16181.0, 2971.0],
 [1067.0, 170.0],
 [2886.0, 726.0],
 [1560.0, 451.0],
 [1478.0, 251.0],
 [894.0, 203.0],
 [5785.0, 1035.0],
 [1562.0, 275.0],
 [2770.0, 406.0],
 [1980.0, 226.0],
 [848.0, 186.0],
 [1308.0, 286.0],
 [9998.0, 1874.0],
 [1212.0, 251.0],
 [1782.0, 338.0],
 [1649.0, 369.0],
 [7399.0, 1698.0],
 [9849.0, 1887.0],
 [554.0, 121.0],
 [2003.0, 500.0],
 [1589.0, 380.0],
 [1726.0, 333.0],
 [1287.0, 2

In [62]:
ar1=[1,2,3,4]
ar2=[4,5,6,7]

se1=pd.Series(ar1)
se2=pd.Series(ar2)

print(se1.corr(se2))

1.0
